[package]
name = "subsetter"
version = "0.1.1"
authors = ["Laurenz Maedje <laurmaedje@gmail.com>, Laurenz Stampfl <laurenz.stampfl@gmail.com>"]
edition = "2021"
description = "Reduces the size and coverage of OpenType fonts."
repository = "https://github.com/typst/subsetter"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = ["compression", "encoding"]
keywords = ["subsetting", "OpenType", "PDF"]
exclude = ["fonts/*"]

[dev-dependencies]
skrifa = "0.19.1"
ttf-parser = "0.21.1"

