[package]
name = "subsetter"
version = "0.1.1"
authors = ["Laurenz <laurmaedje@gmail.com>"]
edition = "2021"
description = "Reduces the size and coverage of OpenType fonts."
repository = "https://github.com/typst/subsetter"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = ["compression", "encoding"]
keywords = ["subsetting", "OpenType", "PDF"]
exclude = ["fonts/*"]

[dev-dependencies]
hex = "0.4.3"
sha2 = "0.10.8"
ttf-parser = "0.20.0"

[dependencies]
pico-args = "0.5.0"
