[package]
name = "subsetter"
version = "0.1.1"
authors = ["Laurenz Maedje <laurmaedje@gmail.com>, Laurenz Stampfl <laurenz.stampfl@gmail.com>"]
edition = "2021"
description = "Reduces the size and coverage of OpenType fonts."
repository = "https://github.com/typst/subsetter"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = ["compression", "encoding"]
keywords = ["subsetting", "OpenType", "PDF"]
exclude = ["fonts/*"]

[dev-dependencies]
skrifa = "0.19.1"
ttf-parser = {git = "https://github.com/LaurenzV/freetype-rs", branch = "gvar-fix"}
freetype-rs = {git = "https://github.com/LaurenzV/freetype-rs"}
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.10.0"
walkdir = "2.5.0"

