name: Continuous integration
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install fonttools
        run: pip install fonttools==4.50
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
        name: Build
      - run: cargo test --release
        name: Run tests
