name: Continuous integration
on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install fonttools
        run: pip install fonttools==4.50
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
        name: Build
      - run: cargo test --release
        name: Run tests

  checks:
    name: Check clippy, formatting, and documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo clippy
      - run: cargo fmt --check --all
      - run: cargo doc --workspace --no-deps